#!/bin/sh
#
# Inital Setup see:
#    https://asciidoctor.org/docs/asciidoctor-revealjs/

SRCFILES=(index.adoc)
for SRCFILE in "${SRCFILES[@]}"; do

echo "Rendering $SRCFILE"
bundle exec asciidoctor-revealjs -r asciidoctor-diagram  -a revealjsdir=https://cdn.jsdelivr.net/npm/reveal.js@3.9.2  slides/$SRCFILE
base=`basename $SRCFILE .adoc`
#echo "Starting Webserver on :8000"
#python -m SimpleHTTPServer >/dev/null 2>&1 & 

#chromium-browser http://localhost:8000/$base.html > /dev/null &

#echo "Watching *.adoc for changes"
#inotifywait -m -e close_write *.adoc |
#while read events; do
#  echo $events
#  bundle exec asciidoctor-revealjs $SRCFILE
#done

done
