site:
  title: Course Project
  url: https://feelpp.github.io/course-project
  start_page: course-project::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs
ui:
  supplemental_files: ./docs/antora/supplemental-ui
  bundle:
    url: https://github.com/feelpp/antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: public
antora:
  extensions:
  - '@antora/collector-extension'
  - '@feelpp/antora-extensions'
asciidoc:
  attributes:
    project_name: Course Project
    project_version: 2.0.2
    page-pagination: '@'
    dynamic-blocks@: ''
    numbered: true
    allow-uri-read: true
    hide-uri-scheme: true
    feelpp: Feel++
    angiotk: AngioTK
    4fastsim: 4FastSim
    stem: latexmath
    hemotumpp: Hemotum++
    eye2brain: Eye2Brain
    swimmer: Swimmer
    python: Python
    cpp: C++
    repository-url: https://github.com/feelpp/course-project
  extensions:
  - '@feelpp/asciidoctor-extensions'
