[.lightbg,background-image="whatiscicd.png",background-opacity=".7"]
== What is CI/CD?

[.notes]
--
At a high level, let's take a look at what we mean by "Continuous Integration" and "Continuous Delivery":
--

=== Continuous Integration

[%step]
* Run a series of scripts automatically, any time changes are pushed
* **Continuously integrate** our changes

[.notes]
--
The idea of continuous integration is being able to check at any time that the code we're working on fits (or "integrates") with the larger codebase.

We do this by defining a number of scripts and the scenarios under which they should run.

IMPORTANT: Especially important on multi-developer teams!
--

=== Continuous Integration

[%step]
* Automated tests
* Coding standards
* Static code analysis
* ...etc.

[.notes]
--
These can be any tests you want to run. Unit tests? Code sniffers to check coding standards? Static code analysis tools — any sort of gate you want to set.

Best of all, these will always be run. No more "oh, I forgot to run the test suite" — make the computer handle it!
--


