= Uncertainty quantification for linear transport
:page-tags: manual,csmi,projects,2026,2026-2027,m2,s3,m2-s3-topic
:page-illustration: fa-solid fa-chart-line
:description: CSMI M2 S3 2026–2027 project proposed by Andrea Thomann.

== Project information

[cols="1,3"]
|===
|Academic year |2026–2027
|Semester |Master 2 — S3
|Project proposer |Andrea Thomann
|Host organisation |IRMA, Université de Strasbourg
|Contact |mailto:andrea.thomann@unistra.fr[andrea.thomann@unistra.fr]
|Team size |One student
|Possible internship |Yes
|Possible PhD |Yes
|===

This project is proposed together with *Mathias Dus*.

== Project context

In this project we consider the influence of a random parameter on the linear transport equation. Therein, the uncertainty can either be on the solution or the model itself by adding a random coefficients to the flux definition. This can be interpreted either by errors in the measurements and uncertainties in the modeling process. Possible applications beyond this project are traffic flow problems as well as many physical processes in random media. This project is together with Mathias DUS.

== Objectives

Understand the model in one dimension (hyperbolic conservation law with intrinsic uncertainty, study some theoretical properties connected to the problem (notion of solution, existence, moments of the solution etc) as well as a numerical implementation based on random finite volume and Monte Carlo. First the linear transport equation is studied, a possible extension to non-linear problems can included depending on the progress of the student.

== Fields

Modelling, simulation, optimisation and control; high-performance computing; uncertainty quantification.

== Mathematical tools

Theory of hyperbolic scalar conservation laws, finite volume scheme (first and second order), solution theory and uncertainty quantification

== Computing tools

HPC (parallelisation of Monte - Carlo approach), Python or C++ implementation

== Topic presentation

* Declared availability for Monday 5 October 2026: *Yes*.
* Preferred format: *In person*.
* xref:2026-2027/m2-s3/presentations.adoc[Presentation schedule for 5 October, 10:00–12:00].

xref:2026-2027/m2-s3/topics/index.adoc[Back to the topic list]
